# Generated by Django 5.2.1 on 2025-07-04 15:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_unit', models.CharField(default='día', help_text='ej: día, hectárea, metro, quintal, etc.', max_length=50, verbose_name='Unidad por Defecto')),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por Defecto')),
                ('requires_invoice', models.BooleanField(default=False, help_text='Si es obligatorio que emitan factura', verbose_name='Requiere Factura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'db_table': 'external_service_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(help_text='Detalle específico del trabajo realizado', verbose_name='Descripción del Trabajo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por Unidad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('other', 'Otro')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='Emitió Factura')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Retención de Impuestos')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='external_payments/contracts/', verbose_name='Contrato/Acuerdo')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='external_payments/invoices/', verbose_name='Archivo de Factura')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago por Servicio Externo',
                'verbose_name_plural': 'Pagos por Servicios Externos',
                'db_table': 'external_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('invoice', 'Factura'), ('receipt', 'Recibo'), ('work_photo', 'Foto del Trabajo'), ('id_copy', 'Copia de Cédula'), ('other', 'Otro')], max_length=15, verbose_name='Tipo de Documento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('file', models.FileField(upload_to='external_payments/documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('external_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='external_payments.externalpayment', verbose_name='Pago Externo')),
            ],
            options={
                'verbose_name': 'Documento de Pago Externo',
                'verbose_name_plural': 'Documentos de Pagos Externos',
                'db_table': 'external_payment_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('identification_type', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte'), ('rise', 'RISE')], default='cedula', max_length=10, verbose_name='Tipo de Identificación')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('has_ruc', models.BooleanField(default=False, verbose_name='Tiene RUC')),
                ('ruc_number', models.CharField(blank=True, max_length=13, verbose_name='Número de RUC')),
                ('has_rise', models.BooleanField(default=False, verbose_name='Tiene RISE')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Razón Social')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Trabajador Externo',
                'verbose_name_plural': 'Trabajadores Externos',
                'db_table': 'external_workers',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='externalpayment',
            name='external_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to='external_payments.externalworker', verbose_name='Trabajador Externo'),
        ),
        migrations.AddField(
            model_name='externalpayment',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='external_payments.servicetype', verbose_name='Tipo de Servicio'),
        ),
    ]
