# Generated by Django 5.2.1 on 2025-07-16 15:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('template_html', models.TextField(verbose_name='HTML de la Plantilla')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Recibo',
                'verbose_name_plural': 'Plantillas de Recibo',
                'db_table': 'payroll_template',
            },
        ),
        migrations.CreateModel(
            name='TipoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tipo')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso/Deducción')], max_length=10, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Rubro',
                'verbose_name_plural': 'Tipos de Rubros',
                'db_table': 'payroll_tipo_rubro',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quincena_numero', models.IntegerField(blank=True, choices=[(1, 'Primera Quincena'), (2, 'Segunda Quincena')], help_text='Solo aplica para períodos quincenales', null=True, verbose_name='Número de Quincena')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Se toma automáticamente del perfil del empleado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Base')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horas Extra')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Factor Horas Extra')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(blank=True, default='Transferencia bancaria', max_length=100, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdelantoQuincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Adelanto')),
                ('fecha_adelanto', models.DateField(verbose_name='Fecha del Adelanto')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('is_descontado', models.BooleanField(default=False, verbose_name='Ya Descontado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos_quincena', to='employees.employee', verbose_name='Empleado')),
                ('payroll_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_descontados', to='payroll.payroll', verbose_name='Nómina donde se descontó')),
            ],
            options={
                'verbose_name': 'Adelanto de Quincena',
                'verbose_name_plural': 'Adelantos de Quincena',
                'db_table': 'payroll_adelanto_quincena',
                'ordering': ['-fecha_adelanto'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Deducción')),
                ('deduction_type', models.CharField(choices=[('tax', 'Impuesto'), ('insurance', 'Seguro'), ('loan', 'Préstamo'), ('union', 'Sindicato'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Es Porcentaje')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payroll', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Deducción de Nómina',
                'verbose_name_plural': 'Deducciones de Nómina',
                'db_table': 'payroll_deduction',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('biweekly', 'Quincenal')], max_length=15, verbose_name='Tipo de Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('pay_date', models.DateField(verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=15, verbose_name='Estado')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'db_table': 'payroll_period',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date', 'period_type')},
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.payrollperiod', verbose_name='Período'),
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rubro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_calculo', models.CharField(choices=[('fijo', 'Monto Fijo'), ('porcentaje', 'Porcentaje del Salario Base'), ('porcentaje_bruto', 'Porcentaje del Salario Bruto'), ('horas', 'Por Horas')], default='fijo', max_length=20, verbose_name='Tipo de Cálculo')),
                ('porcentaje_default', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje por Defecto')),
                ('monto_default', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto por Defecto')),
                ('es_obligatorio', models.BooleanField(default=False, verbose_name='Es Obligatorio')),
                ('aplicar_automaticamente', models.BooleanField(default=False, verbose_name='Aplicar Automáticamente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='payroll.tiporubro', verbose_name='Tipo de Rubro')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'payroll_rubro',
                'ordering': ['tipo_rubro__tipo', 'nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'period')},
        ),
        migrations.CreateModel(
            name='PayrollRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Aplicado')),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas')),
                ('es_adelanto', models.BooleanField(default=False, verbose_name='Es Adelanto')),
                ('fecha_adelanto', models.DateField(blank=True, null=True, verbose_name='Fecha del Adelanto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_aplicados', to='payroll.payroll', verbose_name='Nómina')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='payroll.rubro', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Rubro Aplicado',
                'verbose_name_plural': 'Rubros Aplicados',
                'db_table': 'payroll_rubro_aplicado',
                'unique_together': {('payroll', 'rubro')},
            },
        ),
    ]
