# Generated by Django 5.2.1 on 2025-06-06 14:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('template_html', models.TextField(verbose_name='HTML de la Plantilla')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Recibo',
                'verbose_name_plural': 'Plantillas de Recibo',
                'db_table': 'payroll_template',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salario Base')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Horas Extras')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='Factor Horas Extras')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago Horas Extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Bonificaciones')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comisiones')),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subsidios')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago Bruto')),
                ('income_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Impuesto a la Renta')),
                ('social_security', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Seguridad Social')),
                ('health_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Seguro de Salud')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Otras Deducciones')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Deducciones')),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago Neto')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'payroll_payroll',
                'ordering': ['-period__start_date', 'employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Deducción')),
                ('deduction_type', models.CharField(choices=[('tax', 'Impuesto'), ('insurance', 'Seguro'), ('loan', 'Préstamo'), ('union', 'Sindicato'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Es Porcentaje')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payroll', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Deducción de Nómina',
                'verbose_name_plural': 'Deducciones de Nómina',
                'db_table': 'payroll_deduction',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('biweekly', 'Quincenal'), ('weekly', 'Semanal'), ('daily', 'Diaria')], max_length=15, verbose_name='Tipo de Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('pay_date', models.DateField(verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=15, verbose_name='Estado')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'db_table': 'payroll_period',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date', 'period_type')},
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.payrollperiod', verbose_name='Período'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'period')},
        ),
    ]
