# Generated by Django 5.2.1 on 2025-07-18 23:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='task_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total ganado por tareas completadas (se calcula automáticamente)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ingresos por Tareas'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='aplica_permanentes',
            field=models.BooleanField(default=True, verbose_name='Aplica a Empleados Permanentes'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='aplica_temporales',
            field=models.BooleanField(default=True, verbose_name='Aplica a Empleados Temporales'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Para permanentes: sueldo fijo. Para temporales: se calcula basado en tareas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Base'),
        ),
    ]
