# Generated by Django 5.2.1 on 2025-07-19 00:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_task_earnings_rubro_aplica_permanentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='task_earnings',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='aplica_permanentes',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='aplica_temporales',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Se toma automáticamente del perfil del empleado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Base'),
        ),
    ]
