# Generated by Django 5.2.1 on 2025-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollperiod_quincena_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='quincena_numero',
        ),
        migrations.AddField(
            model_name='payroll',
            name='quincena_numero',
            field=models.IntegerField(blank=True, choices=[(1, 'Primera Quincena'), (2, 'Segunda Quincena')], help_text='Solo aplica para períodos quincenales', null=True, verbose_name='Número de Quincena'),
        ),
    ]
