# Generated by Django 5.2.1 on 2025-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña temporal', verbose_name='Necesita cambiar contraseña'),
        ),
    ]
