# Generated by Django 5.2.1 on 2025-07-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_needs_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Empleado'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='employee', max_length=15, verbose_name='Tipo de Usuario'),
        ),
    ]
