# Generated by Django 5.2.1 on 2025-07-16 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 dígitos. Ejemplo: 1234567890001.', regex='^\\d{13}')], verbose_name='RUC')),
                ('address', models.TextField(max_length=500, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Formato: convencional 02XXXXXXX o celular 09XXXXXXXX.', regex='^0[2-9]\\d{7}$|^09\\d{8}')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'users_company',
            },
        ),
    ]
