# Generated by Django 5.2.1 on 2025-06-06 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Licencia')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('days_allowed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días Permitidos por Año')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requiere Aprobación')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Es Remunerada')),
                ('carry_forward', models.BooleanField(default=False, verbose_name='Transferible al Siguiente Año')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color (Hex)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Licencia',
                'verbose_name_plural': 'Tipos de Licencias',
                'db_table': 'leaves_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('days_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Solicitados')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=15, verbose_name='Estado')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='Aprobado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Empleado')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='Tipo de Licencia')),
            ],
            options={
                'verbose_name': 'Solicitud de Licencia',
                'verbose_name_plural': 'Solicitudes de Licencias',
                'db_table': 'leaves_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('allocated_days', models.IntegerField(default=0, verbose_name='Días Asignados')),
                ('used_days', models.IntegerField(default=0, verbose_name='Días Utilizados')),
                ('remaining_days', models.IntegerField(default=0, verbose_name='Días Restantes')),
                ('carried_forward', models.IntegerField(default=0, verbose_name='Días Transferidos')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Empleado')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='Tipo de Licencia')),
            ],
            options={
                'verbose_name': 'Balance de Licencias',
                'verbose_name_plural': 'Balances de Licencias',
                'db_table': 'leaves_balance',
                'ordering': ['-year', 'employee__employee_number'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
