# Generated by Django 5.2.1 on 2025-07-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'Permanente - Sueldo Fijo'), ('temporary', 'Temporal - Pago por Tareas')], default='permanent', max_length=15, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Para empleados permanentes: sueldo fijo mensual. Para temporales: tarifa base por hora (opcional)', max_digits=10, verbose_name='Salario/Tarifa Base'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='employee_documents/%Y/%m/', verbose_name='Archivo'),
        ),
    ]
