# Generated by Django 5.2.1 on 2025-06-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Beneficio',
                'verbose_name_plural': 'Categorías de Beneficios',
                'db_table': 'benefits_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Deducción')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Monto Fijo'), ('percentage', 'Porcentaje del Salario'), ('progressive', 'Escala Progresiva')], default='fixed', max_length=15, verbose_name='Tipo de Cálculo')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto/Porcentaje')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('biweekly', 'Quincenal'), ('weekly', 'Semanal'), ('annual', 'Anual'), ('one_time', 'Una Sola Vez')], default='monthly', max_length=15, verbose_name='Frecuencia')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Máximo')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Mínimo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deducción',
                'verbose_name_plural': 'Deducciones',
                'db_table': 'benefits_deduction',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Beneficio')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Monto Fijo'), ('percentage', 'Porcentaje del Salario'), ('formula', 'Fórmula Personalizada')], default='fixed', max_length=15, verbose_name='Tipo de Cálculo')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto/Porcentaje')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('biweekly', 'Quincenal'), ('weekly', 'Semanal'), ('annual', 'Anual'), ('one_time', 'Una Sola Vez')], default='monthly', max_length=15, verbose_name='Frecuencia')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Gravable')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Máximo')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Mínimo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='benefits.benefitcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'db_table': 'benefits_benefit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Personalizado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.benefit', verbose_name='Beneficio')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_benefits', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Beneficio de Empleado',
                'verbose_name_plural': 'Beneficios de Empleados',
                'db_table': 'benefits_employee_benefit',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Personalizado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.deduction', verbose_name='Deducción')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_deductions', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Deducción de Empleado',
                'verbose_name_plural': 'Deducciones de Empleados',
                'db_table': 'benefits_employee_deduction',
                'ordering': ['-start_date'],
            },
        ),
    ]
