# Generated by Django 5.2.1 on 2025-06-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('payroll', 'Nómina'), ('attendance', 'Asistencia'), ('benefits', 'Beneficios'), ('deductions', 'Deducciones'), ('leaves', 'Licencias'), ('summary', 'Resumen'), ('custom', 'Personalizado')], max_length=15, verbose_name='Tipo de Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('query', models.TextField(verbose_name='Consulta SQL/QuerySet')),
                ('fields', models.JSONField(default=list, verbose_name='Campos a Incluir')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros Disponibles')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Formato por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'db_table': 'reports_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=15, verbose_name='Estado')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Archivo Generado')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='reports.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Generación de Reporte',
                'verbose_name_plural': 'Generaciones de Reportes',
                'db_table': 'reports_generation',
                'ordering': ['-created_at'],
            },
        ),
    ]
