# Generated by Django 5.2.1 on 2025-06-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('template_subject', models.CharField(max_length=200, verbose_name='Plantilla del Asunto')),
                ('template_body', models.TextField(verbose_name='Plantilla del Cuerpo')),
                ('is_email', models.BooleanField(default=True, verbose_name='Enviar por Email')),
                ('is_system', models.BooleanField(default=True, verbose_name='Notificación del Sistema')),
                ('auto_send', models.BooleanField(default=True, verbose_name='Envío Automático')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'db_table': 'notifications_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email Destinatario')),
                ('cc_emails', models.TextField(blank=True, verbose_name='Emails CC (separados por coma)')),
                ('bcc_emails', models.TextField(blank=True, verbose_name='Emails BCC (separados por coma)')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('html_body', models.TextField(blank=True, verbose_name='Cuerpo HTML')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('retry', 'Reintentando')], default='pending', max_length=10, verbose_name='Estado')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de Reenvío')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máximo de Reintentos')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email en Cola',
                'verbose_name_plural': 'Emails en Cola',
                'db_table': 'notifications_email_queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_33ed25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('unread', 'No Leída'), ('read', 'Leída'), ('archived', 'Archivada')], default='unread', max_length=10, verbose_name='Estado')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype', verbose_name='Tipo de Notificación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
