# Generated by Django 5.2.1 on 2025-07-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_leave_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Licencias')),
                ('receive_payroll_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Nómina')),
                ('receive_adelanto_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Adelantos')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('system_enabled', models.BooleanField(default=True, verbose_name='Notificaciones del Sistema')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de Horas Silenciosas')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin de Horas Silenciosas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'notifications_preferences',
            },
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_queue', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('view', 'Ver'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('edit', 'Editar'), ('download', 'Descargar'), ('none', 'Sin Acción')], default='view', max_length=20, verbose_name='Tipo de Acción'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL de Acción'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira en'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='color',
            field=models.CharField(default='primary', max_length=20, verbose_name='Color Bootstrap'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='icon',
            field=models.CharField(default='fa-bell', max_length=50, verbose_name='Icono FontAwesome'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
